### ISSUE TITLE
One of your three mods (SASSOT, Armor Restitched, Progressive Archery) or maybe all of them causes huge issues in modpack

### ISSUE THREAD

**Issue by rustedgoldmc** [SolipIngen/minecraft.sassot#64]
I am preparing a modpack to play with my friends in 1.21. The modpack I had worked perfectly but I was waiting for some mods I've previously enjoyed, including yours, to update. When they updated I gleefully added all three and immediately discovered that they were causing some issues I've had in the past; essentially, they were causing the server to just not do what it was meant to do i.e. my thirst bars weren't going down (from tough as nails mod), I couldn't open my backpack (from traveler's backpacks) and after a minute whenever I'd break a block it wouldn't drop anything. When I'd inevitably close my game, it would be stuck infinitely saving the game and I had to force quit. When I'd open it again, I'd once more find myself in the place I had been before downloading your mods and loading the game.
I removed the mods and the game worked perfectly. I don't have any ideas what the issue is, and I have nowhere near the technical knowledge required to find out, but if you have any ideas or any of the mods I have installed have known incompatibilities I'd love to know so I can use the mods again because I've really enjoyed playing with them in the past. I didn't test if it was one of the three causing the issue or whether all three did because I honestly just wanted to play Minecraft. Anyways, thanks for reading, I'll attach my modpack (without the three mods because I don't have them downloaded right now).
[Fabric 1.21.zip](https://github.com/user-attachments/files/16104100/Fabric.1.21.zip)

**Comment by SolipIngen** [comment]
Thank you for reporting this Issue.

The latest hotfix updates **(Progressive Archery v1.2.0.c-1.21; SASSOT v1.2.0.a-1.21; Armor Restitched v1.2.0.b-1.21)**, should have fixed at least the bugs that I have found related to this Issue.

I've managed to track down at least one cause for the described problem. Essentially, when SASSOT/Armor Restitched tried to initialise certain mobs and spawn them, it conflicted with initialisation methods with either other mods in your modpack, or with some specific case of the vanilla code. Everything that you have described are symptoms of such initialisation bugs -- the server gets confused on how to spawn the mob, so it gets stuck in a logical loop and desyncs with the client.

Please feel free to update in this thread if such bugs occur again. To speed up the process, if such bugs do happen, please describe in detail what the current loaded chunks and mobs look like, and which of the three mods were turned on.

If there are no further updates within the next few days, I will close this Issue.
Thank you for enjoying my mods, it's great to hear someone enjoying them with friends.

**Comment by rustedgoldmc** [comment]
Thank you for commenting! I tested the modpack again with all three of your mods installed and unfortunately, it's still happening. Historically it's taken a few real life days and several logs in and out of Minecraft for the actually gamebreaking issues to start showing up, so when I noticed my thirst bar wasn't going down and the temperature meter wasn't working (which are the first signs) I just played normally for a bit. I'll be attaching several screenshots of the chunks I've spent the past while in and giving a bit of description as well. 

![image](https://github.com/SolipIngen/minecraft.sassot/assets/83943239/55bc6c00-6571-4fa9-adf7-d51fc92e71b3)
This is where I've spent the past several Minecraft days. I'm quite the homebody ingame and only leave when I need something, so I've noticed almost everything there. The house is in an orchard biome and the fenced area is split between the orchard biome and a shrublands biome (all from Biomes O'Plenty) and it is bordering a redwood biome, an overgrown greens biome, and a river. I've got a large farm with a lot of the crops from Croptopia and a significant amount of vanilla cows, sheep, and chickens. I also have an orchard of sorts with a bunch of modded trees from BOP.
![image](https://github.com/SolipIngen/minecraft.sassot/assets/83943239/0cb1ff4a-1fe3-4393-a7a6-ed44177965e4)
This is a screenshot of the Xaero's map of my explored chunks. The areas covered in snow are places I've had loaded. 

![image](https://github.com/SolipIngen/minecraft.sassot/assets/83943239/b3f39a3a-3eff-4da3-a4dc-2f712d370de2)
This is me, sitting in the aforementioned frozen river, which is something that should be dropping my temperature significantly. Note that the thirst bar is full and the temperature circle is showing as neutral. 
![image](https://github.com/SolipIngen/minecraft.sassot/assets/83943239/f55f28e4-da69-4995-a8dc-5c27a6f029ca)
This is me immediately after disabling all three of your mods and logging back into Minecraft. Note that my thirst bar has immediately gone down two and a half bars and the temperature is showing as cold.

If you have any idea which mods it may be conflicting with, please do let me know and I'll disable them and test it. I can do without a good portion of my current modpack if it would mean being able to play with yours. Also, please let me know if there's any other information I can provide, I don't know what kind of information would be useful.

**Comment by SolipIngen** [comment]
Hello, apologies for the delay, I've been away for the past week.

This is helpful, it's a quite detailed description of what's happening.

A few follow-up questions:

1. On the screenshot of just the map, it seems like the top-right has yet unloaded chunks. Are you able to generate and load those chunks once you get near them, or is the screenshot how chunk loading has stopped?

2. When the temperature or thirst mechanic breaks, what happens to your surroundings? Specifically, do any surrounding mobs suddenly freeze when the mechanic breaks? Once temperature/thirst stops working, are you able to obtain blocks or their drops when you break them?
For instance, did the squid in the river screenshot suddenly stop moving completely, and were you able to harvest the sugar cane on the shore? 

3. What other intended features in your modpack have not been working? 

Thank you for being patient and taking the time to enjoy my mods. Answers to the above questions will help me a lot in finding out what's going wrong.

**Comment by rustedgoldmc** [comment]
Hello, welcome back! In answer to your questions:
1. I just haven't been there. I haven't noticed any issues with chunk loading.
2. In those screenshots, the surroundings were normal, and everything was functioning fine other than the player temperature and thirst. It's historically taken a while for the gamebreaking issues to show up, as I mentioned previously. I don't know why that would be the case, as it would logically make sense for every problem to show up immediately, but that's what I've observed.
3. Tough as Nails is the only mod I have that adds something that changes how the player plays the game. Most everything else adds blocks or quality of life features. Hence, I only noticed the stuff going on with Tough as Nails at first, until everything got bad enough to break the whole game. 

If it would be helpful, I could reinstall your mods and keep a detailed log of how long it takes for things to start properly breaking, but that would probably take a few days. If you'd like me to do that, please let me know if there's any other information you'd like me to include that I haven't thought of.

Thank you for taking the time to help with this!

**Comment by rustedgoldmc** [comment]
Something I forgot to mention - if videos would be helpful, I could provide those as well. I have the necessary software to record the game.

**Comment by SolipIngen** [comment]
> Something I forgot to mention - if videos would be helpful, I could provide those as well. I have the necessary software to record the game.

Yes, please do. Footage of the bugs would be very helpful.

**Comment by rustedgoldmc** [comment]
Alright, I've also started the log. Once something interesting happens I'll post the document and any videos I capture here.

**Comment by rustedgoldmc** [comment]
Okay, nothing particularly interesting has happened (besides two egg-related crashes, a weird situation where a mod stopped working that I wasn't expecting, and a keybind issue) but it's been about a week so I figured I'd send over the stuff I've collected thus far. 
[documentation of minecraft issues.pdf](https://github.com/user-attachments/files/16370387/documentation.of.minecraft.issues.pdf)
[crash log 1.txt](https://github.com/user-attachments/files/16370389/crash.log.1.txt)
[crash log 2.txt](https://github.com/user-attachments/files/16370391/crash.log.2.txt)
[modpack before paring it down.zip](https://github.com/user-attachments/files/16370393/modpack.before.paring.it.down.zip)

**Comment by rustedgoldmc** [comment]
Okay, at long last, the other two items (which were too large) have been uploaded to my Drive so I can just share the links.
https://drive.google.com/file/d/1c-q0m3HZzM-FKb_ZDCFwfoW6-ZaMBMiq/view?usp=sharing
https://drive.google.com/file/d/1fsLA80mzSejYq8pIIq8yK_QQKNl7ig3y/view?usp=sharing

**Comment by SolipIngen** [comment]
Hello again. Once again, thanks for playing my mods, and for the detailed logs and feedback.

As promised, attached are the current drafts of the upcoming mod update for all three of my mods.
[1.2.1-1.21 Drafts.zip](https://github.com/user-attachments/files/16493022/1.2.1-1.21.Drafts.zip)

I've tested them with your pared down modpack, and it seems stable. The hunger and thirst mechanics function now, at least on my end. 
Also, it seems like some of the other issues logged in your documentation pdf have been resolved for your pared down modpack. For example, when an in-use stack runs out, it automatically switches to the next available stack of the same item. Nothing was done on my end to address that bug, so I'm guessing it was some other mod in the modpack causing it.
A few other fixes and changes are present in these versions as well. They will be detailed once they are officially uploaded.

Please feel free to play around with them and test if they resolve the issues you had found so far. 
I am actually planning on uploading these versions onto Modrinth and CurseForge within the next 24 hours. If there are no further issues by then, I will proceed. Of course, that does not mean you shouldn't report any more issues you find after 24 hours, I'll simply make a hotfix update if that happens.
